
require('marks').setup({
  default_mappings = true,
  signs = true,
  bookmark_0 = { annotate = false, virt_text = 'Bmark 0', },
  bookmark_1 = { annotate = false, virt_text = 'Bmark 1', },
  bookmark_2 = { annotate = false, virt_text = 'Bmark 2', },
  bookmark_3 = { annotate = false, virt_text = 'Bmark 3', },
  -- builtin_marks = {".", "<", ">", "^"},
  -- builtin_marks = {"'", "<", ">", "."},
  cyclic = true,
  refresh_interval = 400,
  sign_priority = {lower=10, uppwer=15, built=8, bookmark=20 },
  -- excluded_filetypes = {},
  excluded_buftypes = {
    -- "terminal",
    "nui",
  },
  mappings = {
    prev            = "<C-,>",
    next            = "<C-.>",
    set_next        = "M,",
    preview         = "M:",
    delete_line     = "Mdl",
    delete_buf      = "Mdb",
    annotate        = "MK",
    toggle          = "M'",
    next_bookmark   = 'MM',
    prev_bookmark   = 'Mm',
    delete_bookmark = 'Mdd',

    set_bookmark0   = 'Mc0',
    set_bookmark1   = 'Mc1',
    set_bookmark2   = 'Mc2',
    set_bookmark3   = 'Mc3',
    set_bookmark4   = 'Mc4',
    set_bookmark5   = 'Mc5',
    set_bookmark6   = 'Mc6',
    set_bookmark7   = 'Mc7',
    set_bookmark8   = 'Mc8',
    set_bookmark9   = 'Mc9',

    next_bookmark0  = 'M0',
    next_bookmark1  = 'M1',
    next_bookmark2  = 'M2',
    next_bookmark3  = 'M3',
    next_bookmark4  = 'M4',
    next_bookmark5  = 'M5',
    next_bookmark6  = 'M6',
    next_bookmark7  = 'M7',
    next_bookmark8  = 'M8',
    next_bookmark9  = 'M9',

    previous_bookmark0 = 'M)',
    previous_bookmark1 = 'M!',
    previous_bookmark2 = 'M@',
    previous_bookmark3 = 'M#',
    previous_bookmark4 = 'M$',
    previous_bookmark5 = 'M%',
    previous_bookmark6 = 'M^',
    previous_bookmark7 = 'M&',
    previous_bookmark8 = 'M*',
    previous_bookmark9 = 'M(',
  }
})
