-- [nfnl] fnl/core.fnl
local _local_1_ = require("nfnl.module")
local autoload = _local_1_.autoload
local core = autoload("nfnl.core")
local mod = {}
do
  vim.keymap.set("", "+", "g_", {desc = "End of line", remap = true})
  require("which-key").add({"+", desc = "End of line", mode = ""})
  vim.keymap.set("", ",", "<leader>", {desc = "<leader>", remap = true})
  require("which-key").add({",", desc = "<leader>", mode = ""})
  vim.keymap.set("", ",;", ",", {desc = "prev motion backwards", remap = false})
  require("which-key").add({",;", desc = "prev motion backwards", mode = ""})
  vim.keymap.set("", "<enter>", ",", {desc = "prev motion backwards", remap = false})
  require("which-key").add({"<enter>", desc = "prev motion backwards", mode = ""})
  vim.keymap.set("", "x", "\"xx", {desc = "[delete] character", remap = false})
  require("which-key").add({"x", desc = "[delete] character", mode = ""})
  vim.keymap.set("c", "<C-S-k>", "<C-c>D<C-c>", {desc = "", remap = false})
  require("which-key").add({"<C-S-k>", desc = "", mode = "c"})
  vim.keymap.set("i", "<C-S-b>", "<C-o>B", {desc = "backward whole word", remap = false})
  require("which-key").add({"<C-S-b>", desc = "backward whole word", mode = "i"})
  vim.keymap.set("i", "<C-S-f>", "<C-o>W", {desc = "forward whole word", remap = false})
  require("which-key").add({"<C-S-f>", desc = "forward whole word", mode = "i"})
  vim.keymap.set("i", "<C-S-g>", "<C-g>u", {desc = "new undo point", remap = false})
  require("which-key").add({"<C-S-g>", desc = "new undo point", mode = "i"})
  vim.keymap.set("i", "<C-S-k>", "<C-g>u<C-o>D", {desc = "delete to end of line", remap = false})
  require("which-key").add({"<C-S-k>", desc = "delete to end of line", mode = "i"})
  vim.keymap.set("i", "<C-S-t>", "<C-d>", {desc = "remove indent", remap = false})
  require("which-key").add({"<C-S-t>", desc = "remove indent", mode = "i"})
  vim.keymap.set("i", "<C-S-u>a", "<C-g>u", {desc = "new undo point", remap = false})
  require("which-key").add({"<C-S-u>a", desc = "new undo point", mode = "i"})
  vim.keymap.set("i", "<C-S-u>r", "<C-o><C-r>", {desc = "redo", remap = false})
  require("which-key").add({"<C-S-u>r", desc = "redo", mode = "i"})
  vim.keymap.set("i", "<C-S-u>u", "<C-o>u", {desc = "undo", remap = false})
  require("which-key").add({"<C-S-u>u", desc = "undo", mode = "i"})
  vim.keymap.set("i", "<C-u>", "<C-g>u<C-u>", {desc = "[delete] chars before cursor", remap = false})
  require("which-key").add({"<C-u>", desc = "[delete] chars before cursor", mode = "i"})
  vim.keymap.set("i", "jk", "<ESC>", {desc = "exit Insert[m ]", remap = false})
  require("which-key").add({"jk", desc = "exit Insert[m ]", mode = "i"})
  vim.keymap.set("n", "`", "@=(foldlevel('.')?'za':\"<Space>\")<CR>", {desc = "fold", remap = false})
  require("which-key").add({"`", desc = "fold", mode = "n"})
  vim.keymap.set("n", "/", "/\\v\\c", {desc = "search vmagic", remap = false})
  require("which-key").add({"/", desc = "search vmagic", mode = "n"})
  vim.keymap.set("n", "<C-S-E>", "ge", {desc = "end of previous word", remap = false})
  require("which-key").add({"<C-S-E>", desc = "end of previous word", mode = "n"})
  vim.keymap.set("n", "<C-S-H>", "<C-w>h", {desc = "left pane", remap = false})
  require("which-key").add({"<C-S-H>", desc = "left pane", mode = "n"})
  vim.keymap.set("n", "<C-S-J>", "<C-w>j", {desc = "down pane", remap = false})
  require("which-key").add({"<C-S-J>", desc = "down pane", mode = "n"})
  vim.keymap.set("n", "<C-S-K>", "<C-w>k", {desc = "up Pane", remap = false})
  require("which-key").add({"<C-S-K>", desc = "up Pane", mode = "n"})
  vim.keymap.set("n", "<C-S-L>", "<C-w>l", {desc = "right pane", remap = false})
  require("which-key").add({"<C-S-L>", desc = "right pane", mode = "n"})
  vim.keymap.set("n", "<C-S-Tab>", ":tabprevious<CR>", {desc = "previous tab", remap = false})
  require("which-key").add({"<C-S-Tab>", desc = "previous tab", mode = "n"})
  vim.keymap.set("n", "<C-S-g>", ":FloatermToggle<CR>", {desc = "[!]float term", remap = false})
  require("which-key").add({"<C-S-g>", desc = "[!]float term", mode = "n"})
  vim.keymap.set("n", "<C-S-s>", ":%s/\\v", {desc = "substitute +char +vmagic", remap = false})
  require("which-key").add({"<C-S-s>", desc = "substitute +char +vmagic", mode = "n"})
  vim.keymap.set("n", "<C-Tab>", ":tabnext<CR>", {desc = "next tab", remap = false})
  require("which-key").add({"<C-Tab>", desc = "next tab", mode = "n"})
  vim.keymap.set("n", "<C-n>", ":NERDTreeToggle<CR>", {desc = "[!]NerdTree", remap = false})
  require("which-key").add({"<C-n>", desc = "[!]NerdTree", mode = "n"})
  vim.keymap.set("n", "<C-s>", ":%s/\\v\\c", {desc = "substitute i", remap = false})
  require("which-key").add({"<C-s>", desc = "substitute i", mode = "n"})
  vim.keymap.set("n", "<C-w>n", "new<ESC><C-w>L", {desc = "new buffer right", remap = false})
  require("which-key").add({"<C-w>n", desc = "new buffer right", mode = "n"})
  vim.keymap.set("n", "<esc>", "<CMD>nohlsearch<CR>", {desc = "clear", remap = false})
  require("which-key").add({"<esc>", desc = "clear", mode = "n"})
  vim.keymap.set("n", "?", "?\\v\\c", {desc = "search +back +vmagic", remap = false})
  require("which-key").add({"?", desc = "search +back +vmagic", mode = "n"})
  vim.keymap.set("n", "ZC", ":bd<CR>", {desc = "delete buffer", remap = false})
  require("which-key").add({"ZC", desc = "delete buffer", mode = "n"})
  vim.keymap.set("n", "ZG", ":wqall<CR>", {desc = "write quit all", remap = false})
  require("which-key").add({"ZG", desc = "write quit all", mode = "n"})
  vim.keymap.set("n", "ZQ", ":q!<CR>", {desc = "!quit all", remap = false})
  require("which-key").add({"ZQ", desc = "!quit all", mode = "n"})
  vim.keymap.set("n", "gne", ":GotoNextFunctionEnd<CR>", {desc = "next function end", remap = false})
  require("which-key").add({"gne", desc = "next function end", mode = "n"})
  vim.keymap.set("n", "|", "/\\V\\c", {desc = "search nomagic", remap = false})
  require("which-key").add({"|", desc = "search nomagic", mode = "n"})
  vim.keymap.set("t", "<C-S-g>", "<C-w>:FloatermToggle<ESC>", {desc = "[!]Float Term", remap = true})
  require("which-key").add({"<C-S-g>", desc = "[!]Float Term", mode = "t"})
  vim.keymap.set("t", "<C-w>", "<C-\\><C-n>", {desc = "normal mode", remap = true})
  require("which-key").add({"<C-w>", desc = "normal mode", mode = "t"})
  vim.keymap.set("v", "<C-S-s>", ":s/\\%V\\v", {desc = "sub +vmagic", remap = false})
  require("which-key").add({"<C-S-s>", desc = "sub +vmagic", mode = "v"})
  vim.keymap.set("v", "<C-s>", ":s/\\%V\\v\\c", {desc = "sub +i +vmagic", remap = false})
  require("which-key").add({"<C-s>", desc = "sub +i +vmagic", mode = "v"})
  vim.keymap.set("v", "`", "zf", {desc = "toggle fold", remap = false})
  require("which-key").add({"`", desc = "toggle fold", mode = "v"})
  vim.keymap.set({"n", "v"}, "](", ":call search('(', 'Wsz')<CR>", {desc = "previous (", remap = false})
  require("which-key").add({"](", desc = "previous (", mode = {"n", "v"}})
  vim.keymap.set({"n", "v"}, "])", ":call search(')', 'Wsz')<CR>", {desc = "previous )", remap = false})
  require("which-key").add({"])", desc = "previous )", mode = {"n", "v"}})
  vim.keymap.set({"n", "v"}, "[(", ":call search('(', 'bWsz')<CR>", {desc = "next (", remap = false})
  require("which-key").add({"[(", desc = "next (", mode = {"n", "v"}})
  vim.keymap.set({"n", "v"}, "[)", ":call search(')', 'bWsz')<CR>", {desc = "next )", remap = false})
  require("which-key").add({"[)", desc = "next )", mode = {"n", "v"}})
  vim.keymap.set({"x", "n"}, "ga", "<Plug>(EasyAlign)", {desc = "easy align", remap = false})
  require("which-key").add({"ga", desc = "easy align", mode = {"x", "n"}})
  vim.keymap.set({"c", "i"}, "<C-a>", "<home>", {desc = "start of line", remap = false})
  require("which-key").add({"<C-a>", desc = "start of line", mode = {"c", "i"}})
  vim.keymap.set({"c", "i"}, "<C-b>", "<left>", {desc = "backward char", remap = false})
  require("which-key").add({"<C-b>", desc = "backward char", mode = {"c", "i"}})
  vim.keymap.set({"c", "i"}, "<C-e>", "<end>", {desc = "end of line", remap = false})
  require("which-key").add({"<C-e>", desc = "end of line", mode = {"c", "i"}})
  vim.keymap.set({"c", "i"}, "<C-f>", "<right>", {desc = "forward char", remap = false})
  require("which-key").add({"<C-f>", desc = "forward char", mode = {"c", "i"}})
  vim.keymap.set({"c", "i"}, "<C-w>", "<S-right>", {desc = "forward word", remap = false})
  require("which-key").add({"<C-w>", desc = "forward word", mode = {"c", "i"}})
  vim.keymap.set({"c", "i"}, "<C-S-w>", "<S-left>", {desc = "backward word", remap = false})
  require("which-key").add({"<C-S-w>", desc = "backward word", mode = {"c", "i"}})
  vim.keymap.set({"c", "i"}, "<C-BS>", "<C-w>", {desc = "delete word backwards", remap = false})
  require("which-key").add({"<C-BS>", desc = "delete word backwards", mode = {"c", "i"}})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-1>", "1gt", {desc = "go to tab 1", remap = false})
  require("which-key").add({"<C-1>", desc = "go to tab 1", mode = {"n", "v", "t", "i"}})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-2>", "2gt", {desc = "go to tab 2", remap = false})
  require("which-key").add({"<C-2>", desc = "go to tab 2", mode = {"n", "v", "t", "i"}})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-3>", "3gt", {desc = "go to tab 3", remap = false})
  require("which-key").add({"<C-3>", desc = "go to tab 3", mode = {"n", "v", "t", "i"}})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-4>", "4gt", {desc = "go to tab 4", remap = false})
  require("which-key").add({"<C-4>", desc = "go to tab 4", mode = {"n", "v", "t", "i"}})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-5>", "5gt", {desc = "go to tab 5", remap = false})
  require("which-key").add({"<C-5>", desc = "go to tab 5", mode = {"n", "v", "t", "i"}})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-6>", "6gt", {desc = "go to tab 6", remap = false})
  require("which-key").add({"<C-6>", desc = "go to tab 6", mode = {"n", "v", "t", "i"}})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-7>", "7gt", {desc = "go to tab 7", remap = false})
  require("which-key").add({"<C-7>", desc = "go to tab 7", mode = {"n", "v", "t", "i"}})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-8>", "8gt", {desc = "go to tab 8", remap = false})
  require("which-key").add({"<C-8>", desc = "go to tab 8", mode = {"n", "v", "t", "i"}})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-9>", ":tablast<CR>", {desc = "go to last tab", remap = false})
  require("which-key").add({"<C-9>", desc = "go to last tab", mode = {"n", "v", "t", "i"}})
  vim.keymap.set({"n", "x", "o"}, "{", "<CMD>lua require('nvim-treesitter-textobjects.move').goto_previous_start('@fn_decl.outer', 'textobjects')<CR>", {desc = "prev function start", remap = false})
  require("which-key").add({"{", desc = "prev function start", mode = {"n", "x", "o"}})
  vim.keymap.set({"n", "x", "o"}, "}", "<CMD>lua require('nvim-treesitter-textobjects.move').goto_next_start('@fn_decl.outer', 'textobjects')<CR>", {desc = "next function start", remap = false})
  require("which-key").add({"}", desc = "next function start", mode = {"n", "x", "o"}})
end
return mod
