-- [nfnl] fnl/core.fnl
local _local_1_ = require("nfnl.module")
local autoload = _local_1_.autoload
local which_key = require("which-key")
local mod = {}
do
  vim.keymap.set("", "+", "g_", {desc = "End of line", remap = true})
  vim.keymap.set("", ",", "<leader>", {desc = "<leader>", remap = true})
  vim.keymap.set("", ",;", ",", {desc = "", remap = false})
  vim.keymap.set("", "<enter>", ",", {desc = "", remap = false})
  vim.keymap.set("", "x", "\"xx", {desc = "", remap = false})
  vim.keymap.set("c", "<C-S-k>", "<C-c>D<C-c>", {desc = "", remap = false})
  vim.keymap.set("i", "<C-S-b>", "<C-o>B", {desc = "backward whole word", remap = false})
  vim.keymap.set("i", "<C-S-f>", "<C-o>W", {desc = "forward whole word", remap = false})
  vim.keymap.set("i", "<C-S-g>", "<C-g>u", {desc = "new undo point", remap = false})
  vim.keymap.set("i", "<C-S-k>", "<C-g>u<C-o>D", {desc = "delete to end of line", remap = false})
  vim.keymap.set("i", "<C-S-t>", "<C-d>", {desc = "remove indent", remap = false})
  vim.keymap.set("i", "<C-S-u>a", "<C-g>u", {desc = "new undo point", remap = false})
  vim.keymap.set("i", "<C-S-u>r", "<C-o><C-r>", {desc = "redo", remap = false})
  vim.keymap.set("i", "<C-S-u>u", "<C-o>u", {desc = "undo", remap = false})
  vim.keymap.set("i", "<C-u>", "<C-g>u<C-u>", {desc = "del entered chars b4 curs", remap = false})
  vim.keymap.set("i", "jk", "<ESC>", {desc = "exit Insert[m ]", remap = false})
  vim.keymap.set("n", "`", "@=(foldlevel('.')?'za':\"<Space>\")<CR>", {desc = "fold", remap = false})
  vim.keymap.set("n", "/", "/\\v\\c", {desc = "search vmagic", remap = false})
  vim.keymap.set("n", "<C-S-E>", "ge", {desc = "end of previous word", remap = false})
  vim.keymap.set("n", "<C-S-H>", "<C-w>h", {desc = "left pane", remap = false})
  vim.keymap.set("n", "<C-S-J>", "<C-w>j", {desc = "down pane", remap = false})
  vim.keymap.set("n", "<C-S-K>", "<C-w>k", {desc = "up Pane", remap = false})
  vim.keymap.set("n", "<C-S-L>", "<C-w>l", {desc = "right pane", remap = false})
  vim.keymap.set("n", "<C-S-Tab>", ":tabprevious<CR>", {desc = "previous tab", remap = false})
  vim.keymap.set("n", "<C-S-g>", ":FloatermToggle<CR>", {desc = "[!]float term", remap = false})
  vim.keymap.set("n", "<C-S-s>", ":%s/\\v", {desc = "substitute +char +vmagic", remap = false})
  vim.keymap.set("n", "<C-Tab>", ":tabnext<CR>", {desc = "next tab", remap = false})
  vim.keymap.set("n", "<C-n>", ":NERDTreeToggle<CR>", {desc = "[!]NerdTree", remap = false})
  vim.keymap.set("n", "<C-s>", ":%s/\\v\\c", {desc = "substitute i", remap = false})
  vim.keymap.set("n", "<C-w>n", ":new<ESC><C-w>L", {desc = "new buffer right", remap = false})
  vim.keymap.set("n", "<ESC>", ":noh<ESC>:echon \"\"<enter>", {desc = "clear", remap = false})
  vim.keymap.set("n", "?", "?\\v\\c", {desc = "search +back +vmagic", remap = false})
  vim.keymap.set("n", "ZC", ":bd<CR>", {desc = "delete buffer", remap = false})
  vim.keymap.set("n", "ZG", ":wqall<CR>", {desc = "write quit all", remap = false})
  vim.keymap.set("n", "ZQ", ":q!<CR>", {desc = "!quit all", remap = false})
  vim.keymap.set("n", "gne", ":GotoNextFunctionEnd<CR>", {desc = "next function end", remap = false})
  vim.keymap.set("n", "|", "/\\V\\c", {desc = "search nomagic", remap = false})
  vim.keymap.set("t", "<C-S-g>", "<C-w>:FloatermToggle<ESC>", {desc = "[!]Float Term", remap = true})
  vim.keymap.set("t", "<C-w>", "<C-\\><C-n>", {desc = "normal mode", remap = true})
  vim.keymap.set("v", "<C-S-s>", ":s/\\%V\\v", {desc = "sub +vmagic", remap = false})
  vim.keymap.set("v", "<C-s>", ":s/\\%V\\v\\c", {desc = "sub +i +vmagic", remap = false})
  vim.keymap.set("v", "`", "zf", {desc = "", remap = false})
  vim.keymap.set({"n", "v"}, "](", ":call search('(', 'W')<CR>", {desc = "previous (", remap = false})
  vim.keymap.set({"n", "v"}, "])", ":call search(')', 'W')<CR>", {desc = "previous )", remap = false})
  vim.keymap.set({"n", "v"}, "[(", ":call search('(', 'bW')<CR>", {desc = "next (", remap = false})
  vim.keymap.set({"n", "v"}, "[)", ":call search(')', 'bW')<CR>", {desc = "next )", remap = false})
  vim.keymap.set({"x", "n"}, "ga", "<Plug>(EasyAlign)", {desc = "easy align", remap = false})
  vim.keymap.set({"c", "i"}, "<C-a>", "<home>", {desc = "start of line", remap = false})
  vim.keymap.set({"c", "i"}, "<C-b>", "<left>", {desc = "backward char", remap = false})
  vim.keymap.set({"c", "i"}, "<C-e>", "<end>", {desc = "end of line", remap = false})
  vim.keymap.set({"c", "i"}, "<C-f>", "<right>", {desc = "forward char", remap = false})
  vim.keymap.set({"c", "i"}, "<C-w>", "<S-right>", {desc = "forward word", remap = false})
  vim.keymap.set({"c", "i"}, "<C-S-w>", "<S-left>", {desc = "backward word", remap = false})
  vim.keymap.set({"c", "i"}, "<C-BS>", "<C-w>", {desc = "delete word backwards", remap = false})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-1>", "1gt", {desc = "go to tab 1", remap = false})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-2>", "2gt", {desc = "go to tab 2", remap = false})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-3>", "3gt", {desc = "go to tab 3", remap = false})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-4>", "4gt", {desc = "go to tab 4", remap = false})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-5>", "5gt", {desc = "go to tab 5", remap = false})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-6>", "6gt", {desc = "go to tab 6", remap = false})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-7>", "7gt", {desc = "go to tab 7", remap = false})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-8>", "8gt", {desc = "go to tab 8", remap = false})
  vim.keymap.set({"n", "v", "t", "i"}, "<C-9>", ":tablast<CR>", {desc = "go to last tab", remap = false})
  vim.keymap.set({"n", "x", "o"}, "{", "<CMD>lua require('nvim-treesitter-textobjects.move').goto_previous_start('@fn_decl.outer', 'textobjects')<CR>", {desc = "prev function start", remap = false})
  mod.f = vim.keymap.set({"n", "x", "o"}, "}", "<CMD>lua require('nvim-treesitter-textobjects.move').goto_next_start('@fn_decl.outer', 'textobjects')<CR>", {desc = "next function start", remap = false})
end
return mod
